{% set name = "django-webpack-loader" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: af2b634ea11973d093ffb48a402b8838c6201d0e4e4ba9216f97b74e57791e76

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - jinja2
    - python >={{ python_min }}
    - django >=3.2

test:
  imports:
    - webpack_loader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/owais/django-webpack-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparently use webpack with django
  dev_url: https://github.com/owais/django-webpack-loader

extra:
  recipe-maintainers:
    - rxm7706
    - mxr-conda
    - rluria14
    - oblute
