{% set name = "django-webpack-loader" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6e679805e9607b073ee52702d9b426bac1a54609d966131aa434c78602ac050

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - django >=2.0
  run:
    - python >=3.5
    - django >=2.0

test:
  imports:
    - webpack_loader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/owais/django-webpack-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparently use webpack with django
  dev_url: https://github.com/owais/django-webpack-loader

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
