{% set name = "django-webpack-loader" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e34085b7fc4d352e482ff9cf7d09ae4524e730675e25432ab1d25a2dd94e583

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - webpack_loader
    - webpack_loader.contrib
    - webpack_loader.templatetags

about:
  home: https://github.com/owais/django-webpack-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparently use webpack with django
  dev_url: https://github.com/owais/django-webpack-loader

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
