{% set name = "django-webpack-loader" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-webpack-loader-{{ version }}.tar.gz
  sha256: f11b79700d1bfc1299131bdf4ba479c1ec200f83a1400e1a2feb5c2ba7b6f8c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - webpack_loader
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/owais/django-webpack-loader
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparently use webpack with django
  dev_url: https://github.com/owais/django-webpack-loader

extra:
  recipe-maintainers:
    - rxm7706
    - mxr-conda
    - rluria14
    - oblute
